### ISSUE TITLE
Build failes due to "imported and not used" error

### ISSUE THREAD

**Issue by t4ec** [mathaou/termdbms#13]
`go build` does not build project due to following error:

`# sqlite3-viewer/viewer
viewer/viewer.go:8:2: imported and not used: "github.com/mattn/go-runewidth" as runewidth`

Removing this import from code fixes issue and build finishes successfuly.

**Comment by tonypdmtr** [comment]
I removed the line and it builds OK

**Comment by mathaou** [comment]
This is extremely trivial and fixed in the latest update I'm working on so I'll just close it immediately. Anyone else just remove that line in the meantime my bad.

**Comment by mathaou** [comment]
Mind you my latest update isn't pushed to master yet. Should within the next day or so. It's a doozy! Lots of bug fixes and new features (cell editing and serialization among other things!)
