### ISSUE TITLE
Fails to build with 32-bit Go

### ISSUE THREAD

**Issue by tonypdmtr** [mathaou/termdbms#14]
This error when trying to build with 32-bit version of Go.

```
# sqlite3-viewer/viewer
viewer\util.go:269:22: constant 9223372036854775807 overflows int
viewer\util.go:274:22: constant 9223372036854775807 overflows int
viewer\viewer.go:8:2: imported and not used: "github.com/mattn/go-runewidth" as runewidth

```

Builds OK (after removing the unused import) with 64-bit Go.

(Also, I'm on Win7, and the terminal codes do not work with ANSI.)

**Comment by mathaou** [comment]
I'll look into this. I need to ask the devs of the library I'm using about the ANSI codes tho - might need to have a non-fancy output version for situations like that.

**Comment by mathaou** [comment]
@tonypdmtr I just tested the 32 bit version of the app on Windows 10 - I don't have windows 7 handy but it should build at least. I will look into a flag to disable ansi rendering for the 0.5-alpha release.
