### ISSUE TITLE
Databases 

### ISSUE THREAD

**Issue by gedw99** [mathaou/termdbms#20]
There is also Ent that gives a http and GRPC api to the db. 

https://github.com/ent/ent

It supports 5 databases . It’s a ORM though .

**Comment by mathaou** [comment]
This is cool, and it may solve a few problems I have regarding serialization for things like dates and other niche data types.

Thanks for bringing it to my attention!

**Comment by gedw99** [comment]
It’s a code generator. You won’t I think get raw sql access using ENT. Instead you get access to the objects .

having said hat ent has Extensuons and can generate an ERD and swagger and other higher level things out of it. 

So I don’t think ent is what you want if all your trying to build is the equivalent of SQL Navigator , Toad or pgadmin.

I am building a gui for ent over here.

https://github.com/masseelch/elk

If your into it we can collaborate

**Comment by mathaou** [comment]
Send me the repo I'll take a look.

**Comment by gedw99** [comment]
I have not started the gio code in a repo yet . 

I am still get the patterns for how it needs to work sorted out .
