### ISSUE TITLE
No installation instructions + getting started

### ISSUE THREAD

**Issue by fedderw** [mathaou/termdbms#25]
I apologize if this is obvious to Go progammers - but how would one go about installing this on ubuntu (wsl2) with a fresh golang install?

As for getting started instructions, what is the shell command to use it? 

Thanks!

**Comment by mathaou** [comment]
Hello! Thanks for trying the package. Cloning the repo and running "go build" in the root directory should suffice for compilation. From there, I would just copy it into /usr/bin or something if you want it to be globally available. Let me know if that works for you!

**Comment by mathaou** [comment]
The shell command to use it would be 'termdbms'. Here's a basic tl;dr; of the commands:

WASD to move around cells. Also mouse is supported.
Enter to view a cell in full screen
ESC or : to enter edit mode
[UP/K and DOWN/J] to navigate tables
[LEFT/H and RIGHT/L] to navigate columns if there are more than the screen allows.
    Also to control the cursor of the text editor in edit mode

Enter in edit mode to save the contents of the cell
:s in edit mode to save a copy of the database with changes
:s! in edit mode to overwrite the original database with changes

the -h flag has the full list of commands.
