### ISSUE TITLE
Update readme to inform users how to switch between modes

### ISSUE THREAD

**Issue by Ttibsi** [mathaou/termdbms#28]
I can't seem to see in the readme how to change the mode that's listed in the help.

**Comment by mathaou** [comment]
In the keyboard section of the README it says to press esc to enter edit mode.

When in edit mode it also outlines how to enter format mode, sql mode, and query mode. Am I missing something?

**Comment by Ttibsi** [comment]
Oh god, does it? Turns out, I’m the one missing something. Sorry!
