### ISSUE TITLE
runtime error: integer divide by zero

### ISSUE THREAD

**Issue by PierreKieffer** [mathaou/termdbms#3]
Hi @mathaou  
Congrat for this project, I wanted to test because I like terminal based tools.

However, I cannot start sqlite3-viewer : 
```
Caught panic:

runtime error: integer divide by zero

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x4d, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/charmbracelet/bubbletea.(*Program).Start.func2(0xc00017c1b0)
	/home/pierre/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.14.1/tea.go:447 +0xd6
panic(0x71fa60, 0x9937c0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
sqlite3-viewer/viewer.(*TuiModel).CellWidth(...)
	/tmp/app/demo/sqlite-tui/viewer/util.go:33
sqlite3-viewer/viewer.(*TuiModel).GetBaseStyle(0xc000131bb0, 0x6e7db1, 0xc00000c0a8, 0x0)
	/tmp/app/demo/sqlite-tui/viewer/util.go:39 +0x86f
sqlite3-viewer/viewer.handleWidowSizeEvents(0xc000131bb0, 0xc000131810)
	/tmp/app/demo/sqlite-tui/viewer/events.go:39 +0xae
sqlite3-viewer/viewer.TuiModel.Update(0xc00015d0b0, 0xc00015d0e0, 0xc00015d110, 0x7, 0x1, 0x110, 0x44, 0x0, 0x3, 0x0, ...)
	/tmp/app/demo/sqlite-tui/viewer/viewer.go:55 +0xd46
github.com/charmbracelet/bubbletea.(*Program).Start(0xc00017c1b0, 0x0, 0x0)
	/home/pierre/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.14.1/tea.go:589 +0x5b9
main.main()
	/tmp/app/demo/sqlite-tui/main.go:111 +0x39d
```

Setup : 
- debian 10 
- go 1.16 
- xterm 256 activated 

Is there something that I missed?

**Comment by mathaou** [comment]
Generally when I get that error I forgot the put the -p flag with a valid absolute path to .db file

Other than that the program can't find it or some other thing is going on. Not sure if db has sensitive data but if you send it my way I can debug easier.

**Comment by PierreKieffer** [comment]
[database.zip](https://github.com/mathaou/sqlite-tui/files/7104423/database.zip)

Yep, I tried with this toy sample

**Comment by mathaou** [comment]
Much thanks, I'll look at it in the morning.

**Comment by mathaou** [comment]
@PierreKieffer I'm not sure what I did or what the error was, but I fixed a bunch of bugs this morning when I was adding column expansion and now your database works. I cleaned a lot of stuff up so it was likely traces of spaghetti code that was causing the problem.

**Comment by mathaou** [comment]
@PierreKieffer decided to reopen because it was rude of me to close this without verifying that it fixed the issue for you.

**Comment by PierreKieffer** [comment]
Sorry for my late reaction, I was traveling. Far from the keyboard.
Thanks for the fix, I just tested, and the app is functional.
